// src/lib/data.ts
import type { Course, Message } from "./types";

export const universities = [
    "University of New Brunswick (UNB)",
    "Dalhousie University",
    "Saint Mary's University",
    "Acadia University",
    "Mount Allison University",
    "St. Francis Xavier University",
];

export const allCourses: Course[] = [
    // Mathematics
    {
        id: "maac3021",
        name: "Real Analysis",
        code: "MAAC 3021",
        professor: "Dr. Sarah Johnson",
        semester: "Winter 2025",
        year: 3,
        department: "Mathematics",
        currentStudents: 24,
        alumni: 156,
        prospective: 43,
        difficulty: 4.2,
        timeCommitment: 9.5,
        avgGrade: "B+",
        color: "bg-blue-500",
        popularity: 89,
        tags: ["Math", "Proofs", "Analysis"],
        description:
            "A rigorous introduction to real analysis covering limits, continuity, differentiation, and integration.",
    },

    // Computer science
    {
        id: "cs2110",
        name: "Data Structures",
        code: "CS 2110",
        professor: "Dr. Mike Chen",
        semester: "Winter 2025",
        year: 2,
        department: "Computer Science",
        currentStudents: 78,
        alumni: 320,
        prospective: 156,
        difficulty: 3,
        timeCommitment: 7.5,
        avgGrade: "B",
        color: "bg-emerald-500",
        popularity: 98,
        tags: ["Programming", "Algorithms", "Java"],
        description:
            "Fundamental data structures including trees, graphs, and hash tables. Essential for technical interviews.",
    },
    {
        id: "cs2333",
        name: "Algorithms & Complexity",
        code: "CS 2333",
        professor: "Dr. Priya Patel",
        semester: "Winter 2025",
        year: 3,
        department: "Computer Science",
        currentStudents: 60,
        alumni: 210,
        prospective: 85,
        difficulty: 4.5,
        timeCommitment: 10,
        avgGrade: "B-",
        color: "bg-sky-500",
        popularity: 92,
        tags: ["Algorithms", "Theory", "Proofs"],
        description:
            "Design and analysis of algorithms: divide-and-conquer, dynamic programming, greedy, and NP-completeness.",
    },
    {
        id: "cs2383",
        name: "Software Engineering",
        code: "CS 2383",
        professor: "Prof. A. Gomez",
        semester: "Fall 2024",
        year: 3,
        department: "Computer Science",
        currentStudents: 46,
        alumni: 140,
        prospective: 60,
        difficulty: 3.2,
        timeCommitment: 8,
        avgGrade: "B+",
        color: "bg-emerald-600",
        popularity: 87,
        tags: ["Teamwork", "Design", "Testing"],
        description:
            "Practical software engineering: design patterns, testing, maintenance and team projects.",
    },

    // Math / linear algebra
    {
        id: "math2421",
        name: "Linear Algebra",
        code: "MATH 2421",
        professor: "Dr. James Wilson",
        semester: "Winter 2025",
        year: 2,
        department: "Mathematics",
        currentStudents: 62,
        alumni: 245,
        prospective: 103,
        difficulty: 4,
        timeCommitment: 8,
        avgGrade: "B+",
        color: "bg-gray-600",
        popularity: 91,
        tags: ["Linear Algebra", "Matrices", "ML Foundation"],
        description:
            "Vector spaces, matrices, eigenvalues, and linear transformations with applications to machine learning.",
    },

    // Physics / Chemistry / Biology
    {
        id: "phys1001",
        name: "Physics Fundamentals",
        code: "PHYS 1001",
        professor: "Dr. Emily Watson",
        semester: "Winter 2025",
        year: 1,
        department: "Physics",
        currentStudents: 78,
        alumni: 423,
        prospective: 12,
        difficulty: 3.5,
        timeCommitment: 6.8,
        avgGrade: "B+",
        color: "bg-violet-500",
        popularity: 92,
        tags: ["Physics", "Lab", "Mechanics"],
        description:
            "Classical mechanics, thermodynamics, and wave phenomena with hands-on laboratory experience.",
    },
    {
        id: "chem2401",
        name: "Organic Chemistry",
        code: "CHEM 2401",
        professor: "Dr. Robert Brown",
        semester: "Winter 2025",
        year: 2,
        department: "Chemistry",
        currentStudents: 31,
        alumni: 198,
        prospective: 89,
        difficulty: 4.6,
        timeCommitment: 12.3,
        avgGrade: "C+",
        color: "bg-orange-500",
        popularity: 78,
        tags: ["Chemistry", "Reactions", "Mechanisms"],
        description:
            "Structure, properties, and reactions of organic compounds with emphasis on mechanisms.",
    },
    {
        id: "bio1201",
        name: "Introductory Biology",
        code: "BIO 1201",
        professor: "Dr. Rachel Ng",
        semester: "Fall 2024",
        year: 1,
        department: "Biology",
        currentStudents: 120,
        alumni: 520,
        prospective: 200,
        difficulty: 3.4,
        timeCommitment: 7,
        avgGrade: "B",
        color: "bg-green-500",
        popularity: 94,
        tags: ["Biology", "Lab", "Cells"],
        description:
            "Foundational cell biology, genetics, and ecology with weekly lab sessions.",
    },

    // Social sciences / humanities
    {
        id: "econ2103",
        name: "Microeconomics",
        code: "ECON 2103",
        professor: "Dr. Lisa Zhang",
        semester: "Winter 2025",
        year: 2,
        department: "Economics",
        currentStudents: 67,
        alumni: 234,
        prospective: 34,
        difficulty: 3.2,
        timeCommitment: 5.5,
        avgGrade: "B+",
        color: "bg-indigo-500",
        popularity: 85,
        tags: ["Economics", "Markets", "Theory"],
        description:
            "Individual and firm decision-making, market structures, and resource allocation.",
    },
    {
        id: "phil1104",
        name: "Critical Thinking",
        code: "PHIL 1104",
        professor: "Dr. Alex Harper",
        semester: "Winter 2025",
        year: 1,
        department: "Philosophy",
        currentStudents: 89,
        alumni: 567,
        prospective: 23,
        difficulty: 2.8,
        timeCommitment: 4.2,
        avgGrade: "A-",
        color: "bg-yellow-500",
        popularity: 90,
        tags: ["Philosophy", "Logic", "Writing"],
        description:
            "Logic, argumentation, and analytical reasoning skills for academic and everyday contexts.",
    },

    // Engineering / others
    {
        id: "engr1000",
        name: "Intro to Engineering",
        code: "ENGR 1000",
        professor: "Prof. David Yeo",
        semester: "Fall 2024",
        year: 1,
        department: "Engineering",
        currentStudents: 130,
        alumni: 600,
        prospective: 150,
        difficulty: 3.6,
        timeCommitment: 6.5,
        avgGrade: "B",
        color: "bg-neutral-600",
        popularity: 88,
        tags: ["Engineering", "Design", "Teams"],
        description:
            "Project-based intro to engineering design, prototyping, and teamwork.",
    },
    {
        id: "stat2500",
        name: "Probability & Statistics",
        code: "STAT 2500",
        professor: "Dr. Ming Zhao",
        semester: "Winter 2025",
        year: 2,
        department: "Statistics",
        currentStudents: 90,
        alumni: 300,
        prospective: 120,
        difficulty: 3.7,
        timeCommitment: 7,
        avgGrade: "B+",
        color: "bg-rose-500",
        popularity: 86,
        tags: ["Statistics", "Probability", "Data"],
        description:
            "Probability, distributions, hypothesis testing and an introduction to regression.",
    },
    {
        id: "psych1100",
        name: "Introduction to Psychology",
        code: "PSYC 1100",
        professor: "Dr. Amanda Lee",
        semester: "Fall 2024",
        year: 1,
        department: "Psychology",
        currentStudents: 110,
        alumni: 420,
        prospective: 180,
        difficulty: 2.9,
        timeCommitment: 5,
        avgGrade: "B+",
        color: "bg-pink-500",
        popularity: 93,
        tags: ["Psychology", "Behaviour", "Research"],
        description:
            "Survey of psychological science: cognition, development, and social behaviour.",
    },
    {
        id: "hist1010",
        name: "World History I",
        code: "HIST 1010",
        professor: "Dr. Michael Stone",
        semester: "Fall 2024",
        year: 1,
        department: "History",
        currentStudents: 55,
        alumni: 220,
        prospective: 60,
        difficulty: 3.1,
        timeCommitment: 4.5,
        avgGrade: "B",
        color: "bg-amber-500",
        popularity: 75,
        tags: ["History", "Writing", "Analysis"],
        description:
            "A global overview of major civilizations and historical turning points.",
    },

    // Arts & music
    {
        id: "music101",
        name: "Intro to Music Theory",
        code: "MUSC 101",
        professor: "Dr. Clara Rhodes",
        semester: "Winter 2025",
        year: 1,
        department: "Music",
        currentStudents: 34,
        alumni: 120,
        prospective: 40,
        difficulty: 2.6,
        timeCommitment: 4,
        avgGrade: "A-",
        color: "bg-fuchsia-500",
        popularity: 80,
        tags: ["Music", "Theory", "Ear Training"],
        description: "Basics of harmony, scales, and ear training. Great for beginners.",
    },
    {
        id: "art1500",
        name: "Foundations of Visual Art",
        code: "ART 1500",
        professor: "Prof. L. Morgan",
        semester: "Fall 2024",
        year: 1,
        department: "Art",
        currentStudents: 28,
        alumni: 90,
        prospective: 25,
        difficulty: 2.5,
        timeCommitment: 5,
        avgGrade: "A",
        color: "bg-rose-400",
        popularity: 82,
        tags: ["Art", "Drawing", "Studio"],
        description: "Studio-based introduction to drawing, composition, and materials.",
    },
];

export const previewMessages: Message[] = [
    {
        id: 1,
        user: "Sarah Chen",
        userType: "current",
        avatar: "👩‍🎓",
        year: "Year 3",
        message: "Can someone explain epsilon-delta proofs? I'm completely lost on the homework.",
        timestamp: "2:34 PM",
        reactions: [
            { emoji: "🤔", count: 3 },
            { emoji: "👍", count: 2 },
        ],
    },
    {
        id: 2,
        user: "Dr. Mike Rodriguez",
        userType: "alumni",
        avatar: "🎓",
        year: "Alumni '22 (A+)",
        message:
            'I struggled with those too! The key insight is that δ depends on ε. Think of it as: "How close do I need x to be to make f(x) within ε of L?" I can hop on a call if you need.',
        timestamp: "2:36 PM",
        reactions: [
            { emoji: "🙌", count: 8 },
            { emoji: "💡", count: 5 },
        ],
    },
    {
        id: 3,
        user: "Alex Kim",
        userType: "current",
        avatar: "🧑‍🔬",
        year: "Year 3",
        message: "I just uploaded my epsilon-delta cheat sheet to resources. It has step-by-step examples!",
        timestamp: "2:38 PM",
        reactions: [
            { emoji: "⭐", count: 12 },
            { emoji: "🔥", count: 6 },
        ],
    },
];

export const fullMessages: Message[] = [
    ...previewMessages,
    {
        id: 4,
        user: "Jordan Taylor",
        userType: "prospective",
        avatar: "👀",
        year: "Planning Fall 2025",
        message: "As someone considering this course, should I brush up on limits before taking it?",
        timestamp: "2:40 PM",
        reactions: [{ emoji: "🤔", count: 4 }],
    },
    {
        id: 5,
        user: "Prof. Lisa Wang",
        userType: "alumni",
        avatar: "👩‍🏫",
        year: "Alumni '19 (A+)",
        message:
            "Absolutely! Make sure you're rock solid on limits. Also, start thinking in terms of 'for every ε > 0, there exists δ > 0...' early. It becomes second nature.",
        timestamp: "2:42 PM",
        reactions: [
            { emoji: "💯", count: 15 },
            { emoji: "👨‍🏫", count: 3 },
        ],
    },
];
